# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIInferenceStub(object):
    """Task 1: The AI Inference Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/inference.AIInference/AnalyzeSentiment',
                request_serializer=inference__pb2.SentimentRequest.SerializeToString,
                response_deserializer=inference__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.StreamTextGeneration = channel.unary_stream(
                '/inference.AIInference/StreamTextGeneration',
                request_serializer=inference__pb2.GenerationRequest.SerializeToString,
                response_deserializer=inference__pb2.GenerationResponse.FromString,
                _registered_method=True)
        self.SummarizeBatch = channel.stream_unary(
                '/inference.AIInference/SummarizeBatch',
                request_serializer=inference__pb2.BatchRequest.SerializeToString,
                response_deserializer=inference__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.ChatAssistant = channel.stream_stream(
                '/inference.AIInference/ChatAssistant',
                request_serializer=inference__pb2.ChatMessage.SerializeToString,
                response_deserializer=inference__pb2.ChatMessage.FromString,
                _registered_method=True)


class AIInferenceServicer(object):
    """Task 1: The AI Inference Service definition
    """

    def AnalyzeSentiment(self, request, context):
        """Task 2: Unary RPC (Request -> Response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTextGeneration(self, request, context):
        """Task 3: Server-Streaming RPC (Request -> Stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeBatch(self, request_iterator, context):
        """Task 4: Client-Streaming RPC (Stream -> Response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatAssistant(self, request_iterator, context):
        """Task 5: Bidirectional-Streaming RPC (Stream <-> Stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=inference__pb2.SentimentRequest.FromString,
                    response_serializer=inference__pb2.SentimentResponse.SerializeToString,
            ),
            'StreamTextGeneration': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTextGeneration,
                    request_deserializer=inference__pb2.GenerationRequest.FromString,
                    response_serializer=inference__pb2.GenerationResponse.SerializeToString,
            ),
            'SummarizeBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.SummarizeBatch,
                    request_deserializer=inference__pb2.BatchRequest.FromString,
                    response_serializer=inference__pb2.BatchResponse.SerializeToString,
            ),
            'ChatAssistant': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatAssistant,
                    request_deserializer=inference__pb2.ChatMessage.FromString,
                    response_serializer=inference__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.AIInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.AIInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIInference(object):
    """Task 1: The AI Inference Service definition
    """

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.AIInference/AnalyzeSentiment',
            inference__pb2.SentimentRequest.SerializeToString,
            inference__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTextGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inference.AIInference/StreamTextGeneration',
            inference__pb2.GenerationRequest.SerializeToString,
            inference__pb2.GenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/inference.AIInference/SummarizeBatch',
            inference__pb2.BatchRequest.SerializeToString,
            inference__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatAssistant(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.AIInference/ChatAssistant',
            inference__pb2.ChatMessage.SerializeToString,
            inference__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
