user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';

    access_log  /var/log/nginx/access.log  main;

    # gRPC requires HTTP/2
    server {
        listen 80;
        http2 on; 

        location / {
            # This matches the package name 'inference' and service 'AIInference' from your proto
            grpc_pass grpc://grpc_backends;
            error_page 502 = /error502grpc;
        }
    }

    # Round Robin distribution across 3 instances
    upstream grpc_backends {
        server ai-server:50051;
    }
}