# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"<\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\"#\n\x11GenerationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"#\n\x12GenerationResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0c\x42\x61tchRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\" \n\rBatchResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\"\x1b\n\x0b\x43hatMessage\x12\x0c\n\x04text\x18\x01 \x01(\t2\xbf\x02\n\x0b\x41IInference\x12M\n\x10\x41nalyzeSentiment\x12\x1b.inference.SentimentRequest\x1a\x1c.inference.SentimentResponse\x12U\n\x14StreamTextGeneration\x12\x1c.inference.GenerationRequest\x1a\x1d.inference.GenerationResponse0\x01\x12\x45\n\x0eSummarizeBatch\x12\x17.inference.BatchRequest\x1a\x18.inference.BatchResponse(\x01\x12\x43\n\rChatAssistant\x12\x16.inference.ChatMessage\x1a\x16.inference.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTREQUEST']._serialized_start=30
  _globals['_SENTIMENTREQUEST']._serialized_end=62
  _globals['_SENTIMENTRESPONSE']._serialized_start=64
  _globals['_SENTIMENTRESPONSE']._serialized_end=124
  _globals['_GENERATIONREQUEST']._serialized_start=126
  _globals['_GENERATIONREQUEST']._serialized_end=161
  _globals['_GENERATIONRESPONSE']._serialized_start=163
  _globals['_GENERATIONRESPONSE']._serialized_end=198
  _globals['_BATCHREQUEST']._serialized_start=200
  _globals['_BATCHREQUEST']._serialized_end=229
  _globals['_BATCHRESPONSE']._serialized_start=231
  _globals['_BATCHRESPONSE']._serialized_end=263
  _globals['_CHATMESSAGE']._serialized_start=265
  _globals['_CHATMESSAGE']._serialized_end=292
  _globals['_AIINFERENCE']._serialized_start=295
  _globals['_AIINFERENCE']._serialized_end=614
# @@protoc_insertion_point(module_scope)
